[package]
name = "openai-http"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
protocol = { path = "../protocol" }