[package]
name = "desktop-app"
version = "0.1.0"
edition = "2021"
description = "A Tauri App"
# default-run = "app"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5.3", features = [] }

[dependencies]
utils = { path = "../../crates/utils", version = "0.1.0" }
openai-server = { path = "../openai-server" }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tauri = { version = "1.7.0", features = [] }
log = { workspace = true }
env_logger = { workspace = true }
parking_lot = { version = "0.12.3" }
clap = { workspace = true }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
