[package]
name = "openai-server"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
clap = { workspace = true }
candle-core = { workspace = true }
utils = { path = "../../crates/utils", version = "0.1.0" }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["full"] }
worker = { path = "../../crates/worker", version = "0.1.0" }
protocol = { path = "../../crates/protocol", version = "0.1.0" }
models = { path = "../../crates/models", version = "0.1.0" }
contract = { path = "../../crates/contract", version = "0.1.0" }
usage-service = { path = "../../crates/usage-service", version = "0.1.0" }
registry = { path = "../../crates/registry", version = "0.1.0" }

[features]
metal = ["models/metal"]
