[package]
name = "openai-server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true, features = ["full"] }
worker = { path = "../../crates/worker" }
