[package]
name = "p2p-network"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["sync"] }
str0m = "0.6"
log = { workspace = true }
rand = { workspace = true }
prost = { workspace = true }

[features]
default = ["full"]
full = []
